name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install \
            --allow-unauthenticated -y -qq \
            libgtk-3-dev libvte-2.91-dev

      - name: Build
        run: make && ls -l build

      - name: Install
        run: sudo make install

      - name: Run
        run: kermit -v
